#tap "homebrew/bundle"
#tap "homebrew/cask"
#tap "homebrew/cask-versions"
#tap "homebrew/core"
#tap "warrensbox/tap"

# terminal environment related packages
brew "python@3.12"
brew "thefuck"
brew "tmux"
brew "zsh"
cask "iterm2@nightly"

# cli utilities
brew "git"
brew "jq"
brew "nmap"
brew "mas"
brew "ripgrep"
brew "tree"
brew "vim"
brew "watch"

# applications
cask "google-chrome"
cask "obsidian"
cask "spotify"
cask "topnotch"
