# terminal environment related packages
cask "ghostty"
brew "oh-my-posh"
brew "tmux"

# cli utilities
brew "ansible" # enough for casual use
brew "eza"
brew "git"
brew "git-delta"
brew "jq"
brew "neovim"
brew "nmap"
brew "mas"
brew "openssl"
brew "python3"
brew "ripgrep"
brew "thefuck"
brew "tree"
brew "watch"

# fonts
cask "font-fira-code-nerd-font"
cask "font-sn-pro"

# applications
cask "1password"
cask "chatgpt"
cask "google-chrome"
cask "obsidian"
cask "rectangle"
cask "scroll-reverser"
cask "spotify"
cask "topnotch"
